// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdppajxbwrjoapgbvbzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcHBhanhid3Jqb2FwZ2J2YnpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTU4MzgsImV4cCI6MjA2Mzc3MTgzOH0.vlqxRFKb29kgg3XXIdk3W7OFgApKrgCU_8f7UR8lP_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);